services:
  backend:
    build:
      context: .
      dockerfile: crypto_trading_backend/Dockerfile
    ports:
      - "8001:8000" # host:container
    environment:
      - UPDATE_INTERVAL_SECONDS=300
      - FIREBASE_SERVICE_ACCOUNT_PATH=/run/secrets/firebase-service-account.json
    volumes:
      - ./crypto_trading_backend/firebase-service-account.json:/run/secrets/firebase-service-account.json:ro
      - ./crypto_trading_backend/app.sqlite3:/app/crypto_trading_backend/app.sqlite3
    restart: unless-stopped
